#!/bin/bash
set -euo pipefail

# Generate detailed PR description for dependency sync
# Usage: ./generate-pr-description.sh "file1,file2,file3"

CHANGED_FILES="${1:-}"

# Output file for PR description
OUTPUT_FILE=".github/pr-description.md"

# Get current date
CURRENT_DATE=$(date +"%Y-%m-%d")

# Start generating PR description
cat > "$OUTPUT_FILE" << 'EOF'
## 🔄 Dependency Sync from longhabit

This PR synchronizes dependency updates from the upstream [longhabit](https://github.com/s-petr/longhabit) repository.

### 📝 Files Updated

EOF

# List changed files
if [ -n "$CHANGED_FILES" ]; then
  IFS=',' read -ra FILES <<< "$CHANGED_FILES"
  for file in "${FILES[@]}"; do
    case "$file" in
      "README.md")
        echo "- \`README.md\` - Version requirements (Go, Node.js, PocketBase)" >> "$OUTPUT_FILE"
        ;;
      "backend/go.mod")
        echo "- \`backend/go.mod\` - Go dependencies" >> "$OUTPUT_FILE"
        echo "- \`backend/go.sum\` - Go checksums (auto-generated)" >> "$OUTPUT_FILE"
        ;;
      "package.json")
        echo "- \`package.json\` - NPM dependencies (production and dev)" >> "$OUTPUT_FILE"
        echo "- \`package-lock.json\` - NPM lockfile (auto-generated)" >> "$OUTPUT_FILE"
        ;;
      "eslint.config.mjs")
        echo "- \`eslint.config.mjs\` - ESLint configuration" >> "$OUTPUT_FILE"
        ;;
      *)
        echo "- \`$file\`" >> "$OUTPUT_FILE"
        ;;
    esac
  done
fi

# Add dependency change details section
cat >> "$OUTPUT_FILE" << 'EOF'

### 🔍 Dependency Changes

**Backend (Go)**

EOF

# Extract Go dependency changes if go.mod was updated
if [[ "$CHANGED_FILES" == *"backend/go.mod"* ]]; then
  # Get the main dependencies (not indirect)
  if [ -f "backend/go.mod" ]; then
    echo '```' >> "$OUTPUT_FILE"
    grep -A 20 "^require (" backend/go.mod | grep -v "^)" | grep -v "indirect" | sed 's/^//' >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
  fi
else
  echo "_No Go dependency changes_" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << 'EOF'

**Frontend (NPM)**

EOF

# Extract key NPM dependency changes if package.json was updated
if [[ "$CHANGED_FILES" == *"package.json"* ]]; then
  if [ -f "package.json" ]; then
    echo "Key production dependencies:" >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
    # Extract some notable dependencies
    grep -E '"(react|lucide-react|zod|pocketbase)"' package.json | head -5 >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
  fi
else
  echo "_No NPM dependency changes_" >> "$OUTPUT_FILE"
fi

# Add version requirements section
cat >> "$OUTPUT_FILE" << 'EOF'

### ⚙️ Version Requirements

EOF

if [[ "$CHANGED_FILES" == *"README.md"* ]]; then
  # Extract version requirements from README
  if [ -f "README.md" ]; then
    echo "Prerequisites have been updated:" >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
    grep -E "(Go [0-9]+\.[0-9]+\+|Node\.js [0-9]+\+|PocketBase v[0-9]+\.[0-9]+)" README.md | head -3 | sed 's/^[- ]*//' >> "$OUTPUT_FILE"
    echo '```' >> "$OUTPUT_FILE"
  fi
else
  echo "_No version requirement changes_" >> "$OUTPUT_FILE"
fi

# Add testing checklist
cat >> "$OUTPUT_FILE" << 'EOF'

### ✅ Testing Checklist

Before merging this PR, please verify:

- [ ] Backend builds successfully
  ```bash
  npm run build:server
  ```

- [ ] Frontend builds successfully
  ```bash
  npm run build:client
  ```

- [ ] Development servers start without errors
  ```bash
  npm run dev
  ```

- [ ] Type checking passes
  ```bash
  npm run lint
  ```

- [ ] PocketBase admin dashboard is accessible at `http://localhost:8090/_/`

- [ ] Authentication flows work correctly (login, register, verify email)

- [ ] Existing features function as expected

### 🔗 Upstream Reference

Changes sourced from: [longhabit repository](https://github.com/s-petr/longhabit/commits/main)

---

🤖 **Auto-generated by dependency sync workflow** | Last synced: EOF

echo "$CURRENT_DATE" >> "$OUTPUT_FILE"

echo "✅ Generated PR description at: $OUTPUT_FILE"
