app = "saas-template"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8090"
  DB_DIR = "/app/pb_data"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  method = "GET"
  path = "/api/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[mounts]]
  source = "pocketbase_data"
  destination = "/app/pb_data"

[deploy]
  strategy = "rolling"